openapi: "3.0.3"

info:
  title: "Shop Review API Example"
  description: |
    # Features
    - Get reviews
    - Post review
  termsOfService: "https://tastylog.com/terms/"
  contact:
    name: "Customer Support"
    url: "https://tastylog.com/support/"
    email: "support-desk@tastylog.com"
  license:
    name: "MIT Licence"
    url: "https://opensource.org/licenses/MIT"
  version: "1.0.0"

servers:
  - url: "http://localhost:{port}"
    description: "Local development"
    variables:
      port:
        enum: ["3000", "8080"]
        default: "3000"
  - url: "http://it1.tastylog.com"
    description: "Integration Test"
  - url: "https://stg.tastylog.com"
    description: "Staging"
  - url: "https://api.tastylog.com"
    description: "Production"


tags: []

paths: {}

security: []

components: {}

